### ISSUE TITLE
Warn if rule mentioned more than 1 time in ruleorder / localrule

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/snakecharm#107]
Check runtime behaviour and decide what to show:  error or warning.

![image](https://user-images.githubusercontent.com/72933/60815427-4cfd0380-a1a0-11e9-8fcc-f5c31da98a5e.png)

**Comment by sharkovadarya** [comment]
Such code would compile correctly to this: `workflow.ruleorder( "rule1" , "rule1" , "rule1" )`, so, a warning?

**Comment by iromeo** [comment]
And if you run it, does snakemake show any runtime execution errors (not compile errors)?

**Comment by sharkovadarya** [comment]
No errors here.
![image](https://user-images.githubusercontent.com/12707841/61039069-c41bdd00-a3d6-11e9-8d3a-3221e8f6cf8d.png)

**Comment by iromeo** [comment]
Ok, so we could show some warning here
