### ISSUE TITLE
Warn user that they need to configure Python sdk with snakemake to enable all features

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/snakecharm#109]
Warn user that they need to configure Python SDK with snakemake to enable all features. Smart autocompletion & resolve works in `*.smk` files only if Python SDK with snakemake package is configured. This could be not very intuitive for new users.

**Comment by iromeo** [comment]
E.g we could implement `snakemake` facet and detector using `FacetBasedFrameworkDetector`

**Comment by iromeo** [comment]
`ShellcheckSetupNotificationProvider.java` could be useful as example

**Comment by dakochik** [comment]
How to re-enable banner which warms that "Snakemake support is disabled":
* Open `[project_dir]/.idea/snakemake-settings.xml`, where `[project_dir]` is your project directory.
* Search for tag with attribute `smk_support_banner_enabled`.
* Change attribute value to `true` and save changes.

E.g.:
`<component name="SmkProjectSettings" smk_support_banner_enabled="true" />`
