### ISSUE TITLE
Code completion for subworkflow sections names

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/snakecharm#11]
E.g.:
```
subworkflow otherworkflow:
    workdir:
        "../path/to/otherworkflow"
    snakefile:
        "../path/to/otherworkflow/Snakefile"
    configfile:
        "path/to/custom_configfile.yaml"

```

**Comment by iromeo** [comment]
Is related to #66

**Comment by iromeo** [comment]
And do not show keywords which not applicable here:
![image](https://user-images.githubusercontent.com/72933/60686059-67d52c80-9eaf-11e9-81df-48a542567571.png)

**Comment by iromeo** [comment]
@nekit-000000 please add a screenshot with completion and let's close the issue

**Comment by nekit-000000** [comment]
![Screenshot from 2019-07-05 16-23-19](https://user-images.githubusercontent.com/25721619/60725286-5e94a000-9f41-11e9-8d0d-fc131aea148f.png)
![Screenshot from 2019-07-05 16-23-35](https://user-images.githubusercontent.com/25721619/60725289-605e6380-9f41-11e9-883d-5d7f09996a03.png)
