### ISSUE TITLE
Completion for `shadow` level values

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/snakecharm#12]
E.g. `full`, `minimal`, `shallow`, .... See https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html?highlight=shadow#shadow-rules

**Comment by iromeo** [comment]
@nekit-000000 Please attach here a screenshot which demonstrates how the feature works (e.g. show auto-completion list)

**Comment by nekit-000000** [comment]
![shadowSettingsCompletion](https://user-images.githubusercontent.com/25721619/60179820-357c5d00-9827-11e9-92fe-09258895cff0.png)

**Comment by iromeo** [comment]
Feature will be available in 0.4.x plugin verison
