### ISSUE TITLE
Multiple shell sections arguments inspection

### ISSUE THREAD

**Issue by sharkovadarya** [JetBrains-Research/snakecharm#127]
Shell section can only have one argument, anything more than that results in a snakemake compile error.

Example:

    shell: "command1", "command2", "command3"

NB: check a similar inspection for `subworkflow`.

**Comment by iromeo** [comment]
![image](https://user-images.githubusercontent.com/72933/61745311-f13a9900-ada1-11e9-8391-34a51bf3174b.png)
