### ISSUE TITLE
Parsing error for rules after certain Python statements

### ISSUE THREAD

**Issue by sharkovadarya** [JetBrains-Research/snakecharm#130]
![image](https://user-images.githubusercontent.com/12707841/61292738-a84f7700-a7da-11e9-95c7-5ad0003f15cf.png)

Same error wtih a `while` loop:

![image](https://user-images.githubusercontent.com/12707841/61293116-a2a66100-a7db-11e9-8f5f-38fe87efbf58.png)

In case of some other statement, e.g. `print`, everything is parsed correctly:

![image](https://user-images.githubusercontent.com/12707841/61292765-b9988380-a7da-11e9-8c60-fe1b6f46ae5f.png)

**Comment by iromeo** [comment]
please extract decorators part to a separate issue

**Comment by sharkovadarya** [comment]
A separate issue for decorators: https://github.com/JetBrains-Research/snakecharm/issues/138

**Comment by iromeo** [comment]
Done. Implemented on lexer level
