### ISSUE TITLE
How to debug the code with PyCharm?

### ISSUE THREAD

**Issue by LucaMarconato** [JetBrains-Research/snakecharm#137]
I recently started using Snakemake and in particular I use two features:
* I call Python commands directly from the Snakefile;
* I execute external Python scripts (that I wrote) and from the scripts I look at the variable `snakemake.input`.

To run the code within PyCharm I simply created a run configuration which invokes Snakemake and everything works fine.
The problem is when I want to debug. I cannot set graphical breakpoints in the tab "Snakefile" and the breakpoints that I set in the Python files that are called in my Snakefile are simply ignored (even if calling `snakemake --debug` form my run configuration).
The only way in which I can debug the code is explicitly calling the function `breakpoint()` from the code and running Snakemake from a terminal using `snakemake --debug` (so basically outside PyCharm).
Note that once I write a Python script which uses Snakemake, the only natural way to run it is to use Snakemake, otherwise the values of the variable `snakemake.input` would not be found.

Not being able to use the PyCharm debugger is inconvenient to the point that I am considering stopping using Snakemake.

Is it possible to make the PyCharm debugger and Snakemake work together?
If not, what is a good approach to the problem?

Thanks

**Comment by iromeo** [comment]
At the moment it isn't supported, I think we could add this feature later. I need to talk to PyCharm team and play with debugger API. Snakemake internally converts snakefile into a temporary python file and launches it using exec. So it could be an issue for debugging and could require some changes in snakemake to enable debugger support while using PyCharm.

As a temporary workaround, you could try remoted debug feature (only available in PyCharm Professional). Not all features are supported and it works not as smooth as expected:
* it allows to stop at some line inside Snakefile
* view variables values from the context
* evaluate expression also works
* you could place several breakpoints and "resume program" button works as expected
* step into/out doesn't work in my machine
* you have to place a special piece of code before the line where you want to step into (breakpoints from GUI doesn't work)
* navigation from call stack to snakemake file lines doesn't work

Examples:
* 2 break points in snakefile, we are before `print(boooo)` (2nd breakpoint)
![image](https://user-images.githubusercontent.com/72933/61738723-9732d700-ad93-11e9-920b-412e667e94ac.png)
* breakpoint in python method:
![image](https://user-images.githubusercontent.com/72933/61738679-79fe0880-ad93-11e9-8e07-7bf455b15ba1.png)
* run configuration settings (you need to install suggested pydev-pycharm package depending on your PyCharm version and specify some port for debugger). At first press "debug" button
![image](https://user-images.githubusercontent.com/72933/61739111-75861f80-ad94-11e9-9612-6187dfdee8da.png)
* then launch snakemake using terminal or whatever else
![image](https://user-images.githubusercontent.com/72933/61739443-1674da80-ad95-11e9-859e-25b48b15c015.png)

**Comment by iromeo** [comment]
> Not being able to use the PyCharm debugger is inconvenient to the point that I am considering stopping using Snakemake.

I agree that debugger helps but the alternative is to use debug output (temporary `print(...)` statements in code). I normaly run shell scripts from rules so python debugger wont be helpfull for me, only debug output.

**Comment by iromeo** [comment]
related discussion https://groups.google.com/forum/#!topic/snakemake/84emehyiWtg

**Comment by LucaMarconato** [comment]
Thank you for the detailed explanation. I will use the remote debugging. I hope to see the full debugger working in a future release 😊
