### ISSUE TITLE
Decorators parsing error

### ISSUE THREAD

**Issue by sharkovadarya** [JetBrains-Research/snakecharm#138]
`def or @ expected` error on decorators
![image](https://user-images.githubusercontent.com/12707841/61719172-16f97b00-ad6d-11e9-94dc-d200648746b6.png)

Snakemake compiles such code without any errors though.

**Comment by iromeo** [comment]
Decorators indeed require other decorators or function. Snakemake code-generation converts rule to a chain of decorators, so the above example is correct, from syntax point of view. But I don't see any practical sense to support this synthetic example.
