### ISSUE TITLE
Snakecharm incompatible with current PyCharm version.

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [JetBrains-Research/snakecharm#143]
My pycharm just updated (Build #PY-192.5728.105), and now I get the error message:
`Snakecharm incompatible with current PyCharm version.`

**Comment by iromeo** [comment]
Ok, we will update the plugin this week, I hope today. A plugin compatible with PyCharm 2019.2 includes many new features, but it is in "beta" state at the moment.

**Comment by Maarten-vd-Sande** [comment]
That is great news! Thanks!

**Comment by iromeo** [comment]
Done, https://plugins.jetbrains.com/plugin/11947-snakecharm/update/66087

**Comment by iromeo** [comment]
0.4 release change notes - https://github.com/JetBrains-Research/snakecharm/blob/master/CHANGES

P.S: The plugin is in beta state, please report any bugs / missing features.
