### ISSUE TITLE
Unhighlighted syntax error when a function call spans over multiple lines but starts at the same line as section

### ISSUE THREAD

**Issue by sharkovadarya** [JetBrains-Research/snakecharm#148]
This code compiles just fine:

    rule foo:
        input: foo1("text1", "text2", "text3")

This, however, produces a compilation error:

    rule foo:
        input: foo1("text1",
                    "text2", "text3")

While this does not:

    rule foo:
        input:
           foo1("text1",
                "text2", "text3")

Would be nice if such an error was highlighted as it is an easy mistake to make but the Snakemake error message (`Expecting rule keyword, comment or docstrings inside a rule definition.`) is not very helpful.

**Comment by dakochik** [comment]
Fixed:

![multiline func call](https://user-images.githubusercontent.com/55440084/126962161-57f37c53-d68d-49e1-9946-a29b200bd2eb.gif)

**Comment by iromeo** [comment]
@dakochik Please add a demo for the new quickfix

**Comment by dakochik** [comment]
New quickfix:

![multiline func call](https://user-images.githubusercontent.com/55440084/127506680-de9c0dbb-3fed-4d9a-8883-d2f13d9a820f.gif)
