### ISSUE TITLE
Rules and rule params folding support

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/snakecharm#15]
Rules and rule params folding support

**Comment by iromeo** [comment]
E.g. see `shell` arg in:
```
rule download_phantompeakqualtools:
    output: directory("bin/phantompeakqualtools")
    shell: 'cd bin && '
           'curl --location '
           'https://storage.googleapis.com/google-code-archive-downloads/v2/'
           'code.google.com/phantompeakqualtools/ccQualityControl.v.1.1.tar.gz '
           '--output {params.targz} && '
           'tar xvf {params.targz}'
```

**Comment by iromeo** [comment]
Not sure about rule params folding, looks messy
![image](https://user-images.githubusercontent.com/72933/52175976-6a770d00-27bd-11e9-994b-888f1859fa11.png)

Let's fold `rule`,  and python code block containing sections (`run`, `onstart`, `onerror`, `onsuccess`)

**Comment by iromeo** [comment]
Done:

![image](https://user-images.githubusercontent.com/72933/52176090-ef165b00-27be-11e9-859e-9953ea378b05.png)

![image](https://user-images.githubusercontent.com/72933/52176096-fb9ab380-27be-11e9-9f4f-906776d23632.png)

**Comment by winni2k** [comment]
This is really nice!
