### ISSUE TITLE
Inspection quick fixes

### ISSUE THREAD

**Issue by sharkovadarya** [JetBrains-Research/snakecharm#194]
Some inspections might benefit from allowing the user to invoke a quick fix (e.g. rename the rule in case of rule redeclaration, or remove a section if it is overridden by a preceding declaration).

**Comment by iromeo** [comment]
Please describe here all suggested quick fixes, with examples of before/after

**Comment by sharkovadarya** [comment]
**`SmkRuleRedeclarationInspection`: rename rule**

before:
![image](https://user-images.githubusercontent.com/12707841/63088411-8a05a400-bf5d-11e9-80a8-3081a74b8633.png)
after:
![image](https://user-images.githubusercontent.com/12707841/63088492-bf11f680-bf5d-11e9-848d-4abee8c5364f.png)


**`SmkResourcesKeywordArgsInspection`: suggest user to name resource** by adding an `=` before resource value and moving the caret to the left of `=`

(presence of spaces around `=` depends on Python code style settings for the project)
before:
![image](https://user-images.githubusercontent.com/12707841/63088579-10ba8100-bf5e-11e9-98a2-a0a53a637976.png)
after:
![image](https://user-images.githubusercontent.com/12707841/63088705-5f681b00-bf5e-11e9-964d-e55a8b34b030.png)

same thing for **'positional argument after keyword argument' from `SmkSyntaxErrorAnnotator`**

before:
![image](https://user-images.githubusercontent.com/12707841/63090792-0f408700-bf65-11e9-879a-c4d77627397e.png)
after:
![image](https://user-images.githubusercontent.com/12707841/63090876-4fa00500-bf65-11e9-81b7-592166b3a2e9.png)

**`SmkSectionRedeclarationInspection`: remove section or rename section**

_Remove section_

before:
![image](https://user-images.githubusercontent.com/12707841/63090936-7d854980-bf65-11e9-843c-872b0d725516.png)
after:
![image](https://user-images.githubusercontent.com/12707841/63090949-8bd36580-bf65-11e9-9c8b-c35b967a32ca.png)

_Rename section_
(see above for 'before')

after:
![image](https://user-images.githubusercontent.com/12707841/63091020-be7d5e00-bf65-11e9-94c0-a386d53e4043.png)

**`SmkRuleSectionAfterExecutionSectionInspection`: move execution section to the bottom of the rule**

before:
![image](https://user-images.githubusercontent.com/12707841/63091166-39467900-bf66-11e9-8565-0ed3db31bcc3.png)
after:
![image](https://user-images.githubusercontent.com/12707841/63091179-44010e00-bf66-11e9-8efc-9ff55c491b17.png)
