### ISSUE TITLE
Callables can only be used in certain sections

### ISSUE THREAD

**Issue by sharkovadarya** [JetBrains-Research/snakecharm#198]
See also: https://github.com/JetBrains-Research/snakecharm/issues/187

Issue 187 only relates to lambda expressions, but similar statements hold true for any sort of callable: `input`, `group`, `resources`, `threads`, `params` can use callables, while other sections cannot.

    def params_function(wildcards, input, output, threads, resources):
        return "text"

    rule foo:
        input: "file.py"
        params: params_function
        shell: "echo hello {params}"

For example, this would work for `params`, but not for `message`.

**Comment by iromeo** [comment]
![image](https://user-images.githubusercontent.com/72933/90249557-58ab0700-de43-11ea-9322-69594abfcdcb.png)
