### ISSUE TITLE
Inspection for unavailable rule sections in SnakemakeSL

### ISSUE THREAD

**Issue by nekit-000000** [JetBrains-Research/snakecharm#199]
In SnakemakeSL only some rule sections are available. E.g.
```
rule NAME:
  message: "hello"
  shell: "echo {message}"
```
Will fail with an error:

> The name 'message' is unknown in this context.

The list of available sections:
- input 
- output
- version
- threads
- log
- params
- resources

But take into account that this code is valid:
```
message = "goodbye"
rule NAME:
    message: "hello"
    shell: "echo {message}"
```
And it will result in a _goodbye_

**Comment by iromeo** [comment]
I think this should work automatically as a result of unresolved reference on `{message}` in first example

**Comment by iromeo** [comment]
![image](https://user-images.githubusercontent.com/72933/64127862-38ae3f00-cdbc-11e9-94ee-deb56fe5cfd1.png)
