### ISSUE TITLE
Parsing error before unpacked dictionary not highlighted (missing comma)

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/snakecharm#209]
Here comma is missing in `output:` section between `.bam")` and `**unaligned_fq()`
```
rule bismark_align:
    input:
        #**reads_for_pe_or_se_input({}),
        genome=ancient("indexes/{genome}/{genome}.fa"),  # ensure genome.fa exists
        bismark_indexes_dir=ancient(rules.bismark_indexes.output[0]),
    output:
        bam_file=protected("bams/{sample}/{fq_name}_{genome}_pe.bam")
        **unaligned_fq()
    log:
        "bams/{sample}/{fq_name}_{genome}_pe.log"
```

**Comment by sharkovadarya** [comment]
Python example:

    def foo():
        return {'' : 'ff'}

    def bar():
        return 1

    print(1 ** foo())
    print(1, ** foo())

Both of these cases are parsed as valid, in the first `print()` statement `**` is exponential operator, in the second case it's unpacking the dictionary. In case of missing comma it's impossible to distinguish between the two during parsing.

A snakemake example where syntax is the same but there is no missing comma:
  
    resources: 
        a=4
        **9

This is indeed a binary expression.

**Comment by iromeo** [comment]
Not a bug, closed.
