### ISSUE TITLE
Wrong completion list after rules./checkpoints.

### ISSUE THREAD

**Issue by nekit-000000** [JetBrains-Research/snakecharm#211]
![Screenshot from 2019-08-20 18-00-35](https://user-images.githubusercontent.com/25721619/63358925-836b9800-c374-11e9-851f-4d79b839fd66.png)
![Screenshot from 2019-08-20 18-01-36](https://user-images.githubusercontent.com/25721619/63358965-954d3b00-c374-11e9-9681-6536fd3686f2.png)
![Screenshot from 2019-08-20 18-02-18](https://user-images.githubusercontent.com/25721619/63359016-ae55ec00-c374-11e9-81d2-ac4f8bbbb9a3.png)

**Comment by iromeo** [comment]
Fixed
