### ISSUE TITLE
Find usages for rule sections and wildcards

### ISSUE THREAD

**Issue by nekit-000000** [JetBrains-Research/snakecharm#233]
When i put the caret on `sample`:
![Screenshot from 2019-08-26 17-17-34](https://user-images.githubusercontent.com/25721619/63697429-8c9dae80-c825-11e9-911d-7e62f7acb133.png)
I will see:
![Screenshot from 2019-08-26 17-17-23](https://user-images.githubusercontent.com/25721619/63697444-98897080-c825-11e9-8d31-faa0f14d5fb6.png)
And find usages action is also executable:
![Screenshot from 2019-08-26 17-19-36](https://user-images.githubusercontent.com/25721619/63697525-c1aa0100-c825-11e9-817e-5a9453c2636f.png)
Lets implement the same functionality for all rule/checkpoint sections that are available in SnakemakeSL

**Comment by iromeo** [comment]
![image](https://user-images.githubusercontent.com/72933/64119090-b0bb3b80-cda1-11e9-8172-1e6153a1c446.png)
![image](https://user-images.githubusercontent.com/72933/64119159-da746280-cda1-11e9-9a5d-ef6d81bfadd5.png)
