### ISSUE TITLE
Multiline shell commands in anonymous rules defined in loops

### ISSUE THREAD

**Issue by chm-ipmu** [JetBrains-Research/snakecharm#275]
I have an issue whereby valid Snakemake code is marked as an error by Pycharm when multiline shell command are defined in a for-loop (see picture below for a MWE)

![Screenshot from 2020-02-17 11-55-31](https://user-images.githubusercontent.com/56914538/74620505-bacccd00-517c-11ea-8d07-d2346d1b67e4.png)

On mouse-over the error message is "Statement expected, found PY:DEDENT".

The error goes away and syntax highlighting works as expected when the shell command is on one line.

![Screenshot from 2020-02-17 11-59-31](https://user-images.githubusercontent.com/56914538/74620577-00899580-517d-11ea-8ae2-552a570bea10.png)

**Comment by iromeo** [comment]
Thx, I've reproduced it:
```
rule all:
    input: expand("test{i}", i=range(3))

for x in range(3):
    rule:
        output: f'test{x}'
        shell: "python test.py "
               "--output {output}"
```

**Comment by iromeo** [comment]
To be honest, your example is very weird because IMHO here you do some hack instead of using wildcards syntax. To my mind, this is better to write like:
```
rule all:
    input: expand("test{i}", i=range(3))

rule test:
    output: 'test{x}'
    shell: "python test.py "
           "--output {output}"
```

In this case you wan't be get any errors and you'll use snakemake syntax in more natural way. 
<img width="406" alt="Screenshot 2020-02-29 at 21 57 38" src="https://user-images.githubusercontent.com/72933/75613419-94c10880-5b3e-11ea-8ee5-467c8ea0e723.png">

**Comment by chm-ipmu** [comment]
The example was just for the sake of a MWE and is artificial.

The usage of this pattern is legitimate (although I am happy to be corrected) in rules where e.g. all commands are the same but the output is different depending on a single wildcard.

```
files = {"file1.txt": ["file1_a.pdf", "file1_b.pdf"],
         "file2.txt": ["file2_a.pdf"]}

rule all:
    input: files.values()

for input_files, output_files in files.items():
    rule:
        input: input_files
        output: output_files
        shell: "python scripy.py "
               "--input {input} "
               "--output {output} "
               "--many "
               "--other "
               "--flags "
```

**Comment by iromeo** [comment]
Thank you, now it is clear why you need it. I agree that the use case is legitimate and we need to fix parsing here.

**Comment by chm-ipmu** [comment]
Hi - not sure if this is helpful but I just found that the parsing of the shell command is corrected if some python code is put between the "for" line and the "rule:" line, i.e. just below line 7 in the above example
