### ISSUE TITLE
3:42 PM	Plugin Error: Plugin "SnakeCharm" is incompatible (until build 193.SNAPSHOT < PC-201.6668.115).

### ISSUE THREAD

**Issue by arjanvandervelde** [JetBrains-Research/snakecharm#279]
Hi!

I was wondering if this is a temporary situation :) I just updated PyCharm to 2020.1 (community edition) and sadly the snakecharm plugin is no longer compatible.

Thanks!

-- Arjan

**Comment by iromeo** [comment]
@arjanvandervelde Hi, sorry for the inconvenience, we'll release the updated version ASAP, this weekend or earlier. Work in progress.

**Comment by iromeo** [comment]
As a temp workaround you could use 2019.3.4 version, which is compatible

**Comment by arjanvandervelde** [comment]
thank you!

**Comment by iromeo** [comment]
0.6.0.165 released!

**Comment by arjanvandervelde** [comment]
thank you!
