### ISSUE TITLE
PyCharm 2020.2 API changes

### ISSUE THREAD

**Issue by sproshev** [JetBrains-Research/snakecharm#282]
* `PyUtil#getLanguageLevelForVirtualFile` has been moved to `PythonLanguageLevelPusher#getLanguageLevelForVirtualFile`

* PythonDialectsTokenSetProvider is an application service now: `PythonDialectsTokenSetProvider.INSTANCE` -> `PythonDialectsTokenSetProvider.getInstance()`

**Comment by iromeo** [comment]
thx

**Comment by iromeo** [comment]
Done
