### ISSUE TITLE
Unresolved reference for 'rule' in 'run' section

### ISSUE THREAD

**Issue by BertBog** [JetBrains-Research/snakecharm#283]
Hey,

When I'm referencing the 'rule' variable in the python code of the 'run' section, it gets flagged as an unresolved reference, but the code itself works fine.
Would it be possible to fix this? For other variables such as 'threads' or 'input' it works fine.

Best regards,
Bert

**Comment by iromeo** [comment]
@BertBog could you provide a code example for this issue? What `rule` is used for, is it your own variable or some provided by snakemake?

**Comment by BertBog** [comment]
We mainly use it to log information about rule execution to a database. But a basic use case would be something like this:
```
rule do_something:
    output:
        TXT = "test_file.txt"
    run:
        print("Executing rule: {}".format(rule))
        with open(output.TXT, 'w') as handle:
            handle.write('done\n')
```

**Comment by iromeo** [comment]
Oh, I don't know about this feature, thx. I'll add support for it in future versions, need to investigate snakemake sources, what API is available for `rule` variable, what is it's type, etc.

**Comment by iromeo** [comment]
Updated:
This var is available as a parameter of run wrapper function generated by snakemake, e.g.:

```
@workflow.run
def __rule_do_something(input, output, params, wildcards, threads, resources, log, version, rule, conda_env, container_img, singularity_args, use_singularity, env_modules, bench_record, jobid, is_shell, bench_iteration, cleanup_scripts, shadow_dir, edit_notebook):
   ...
```

Run function is generated by snakemake.parser.Run class

**Comment by iromeo** [comment]
Error not shown for 'rule' and 'jobid', also `rule` is in completion list:
![image](https://user-images.githubusercontent.com/72933/81507203-6e6cd580-9304-11ea-9f93-8bc25b728ebb.png)
