### ISSUE TITLE
Missing container directive

### ISSUE THREAD

**Issue by mbhall88** [JetBrains-Research/snakecharm#291]
Snakecharm does not recognise the `container:` directive. This was probably missed as it wasn't in the snakemake changelog originally. See https://github.com/snakemake/snakemake/issues/440 and <https://snakemake.readthedocs.io/en/stable/snakefiles/deployment.html#running-jobs-in-containers>

**Comment by iromeo** [comment]
Hi @mbhall88 thx, I've already added it in https://github.com/JetBrains-Research/snakecharm/commit/3129218be52084a154af276e3e59e17d9ac5a064, the change will be available in next plugin release for PyCharm 2020.2 builds.

**Comment by iromeo** [comment]
Fixed

**Comment by iromeo** [comment]
Good news, it is in release for 2020.1.x. Just released: 0.7.0.209!
