### ISSUE TITLE
Weak warning for useless log section

### ISSUE THREAD

**Issue by dievsky** [JetBrains-Research/snakecharm#300]
Add a weak warning when a useless `log` section is detected. Specifically, when the rule uses `shell` directive, and `log` isn't referenced in the shell command. Maybe it can also be detected in some other cases as well, like with `run`.

Also it could be nice to add a weak warning on a _missing_ log section.

**Comment by iromeo** [comment]
I like the idea. Also could be applicable to `run` section, also harder to do static code analysis

Just a remark: In case of our cluster profile, it uses log section for cluster log even `log` section isn't used by a shell.

**Comment by iromeo** [comment]
E.g.: `unused` log secton:
```
rule:
  log: "foo"
  shell: "echo 123" 
```

ok example:
```
rule:
  log: "foo"
  shell: "echo 123 &> {log}" 
```

**Comment by dakochik** [comment]
Fixed: 

![unused log section](https://user-images.githubusercontent.com/55440084/127613868-5a86b856-41fd-4305-9208-01f54180d6a9.gif)

**Comment by dakochik** [comment]
Updated:

![unused log section](https://user-images.githubusercontent.com/55440084/128136822-609fd58a-df4a-42c7-8291-fd9f92f0829a.gif)
