### ISSUE TITLE
Report parameter not recognised

### ISSUE THREAD

**Issue by mbhall88** [JetBrains-Research/snakecharm#301]
The `report()` parameter `subcategory` is not recognised. See <https://snakemake.readthedocs.io/en/stable/snakefiles/reporting.html> for an example usage.

**Comment by iromeo** [comment]
Could you provide more details, cannot reproduce it:
* Project interpreter in my PyCharm is conda env with snakemake `5.16.0`
* PyCharm successfully resolves `report` to `~/anaconda3/envs/smk/lib/python3.7/site-packages/snakemake/io.py`
* I see proper `report` declaration from `io.py` with `subcategory` named arg
* I don't see any errors/warnings for `subcategory` in my snakefile
* Code completion popup also suggests `subcategory`
![image](https://user-images.githubusercontent.com/72933/90250077-2fd74180-de44-11ea-8c6c-807228b0b6dd.png)

**Comment by mbhall88** [comment]
@iromeo I'm sorry, I didn't realise snakecharm was getting this info from the local snakemake! That's so clever!  

Updating my snakemake version resolved it. Thank you!
