### ISSUE TITLE
not compatible with PyCharm 2020.3

### ISSUE THREAD

**Issue by rababerladuseladim** [JetBrains-Research/snakecharm#337]
My PyCharm instance just upgraded to 2020.3 and unfortunately SnakeCharm was deactivated. :-( 
I hope to see it back, soon. Thank you for your work!

**Comment by iromeo** [comment]
Support will be in comming release 0.9.0

**Comment by iromeo** [comment]
0.9.0 released, see https://github.com/JetBrains-Research/snakecharm/releases/tag/0.9.0.387
