### ISSUE TITLE
How do you configure column width (line length) and/or turn it off?

### ISSUE THREAD

**Issue by nh13** [JetBrains-Research/snakecharm#338]

**Comment by iromeo** [comment]
Hi @nh13,
You mean vertical lines `visual guides`? The plugin uses Python code style settings for snakemake files formating

![image](https://user-images.githubusercontent.com/72933/101681222-e35ae600-3a72-11eb-8f46-dc10c569598f.png)

**Comment by nh13** [comment]
Thanks for the reply!  I'd like to turn hard-wrapping off for just my snakefiles (not other python code), so I guess I want something that is specific to snakecharm versus just inheriting the settings from Python.

**Comment by iromeo** [comment]
Snakemake specific codestyle settings paged added in coming 0.9.0
![image](https://user-images.githubusercontent.com/72933/102180920-b7988f80-3eba-11eb-9b65-3a6b177a8ec8.png)
