### ISSUE TITLE
Snakecharm not compatible with Pycharm version

### ISSUE THREAD

**Issue by joys8998** [JetBrains-Research/snakecharm#350]
Hi there,

Thank you very much for this plugin it saves my life everyday! Unfortunately after the last Pycharm update (2021.1) everything is not working. 
In particular I get this error if I try to install it manually:
 `Plugin 'SnakeCharm' (version '0.9.0.387') is not compatible with the current version of the IDE, because it requires build 203.* or older but the current build is PC-211.6693.115`.

Do you have any solution?

**Comment by iromeo** [comment]
Hi @joys8998 

The only temporary workaround is to use it with 2020.x PyCharm builds. I'll try to fix this approx in 1-2 weeks.

P.S:  Latest Snakemake 5.x and 6.0 releases also refactored snakemake module internals, so SnakeCharm static code analysis stopped working, e.g. `rules.` are highlighted as errors. I want to fix this issue too.

**Comment by joys8998** [comment]
Ok thanks. I downgraded Pycharm as you said!

**Comment by iromeo** [comment]
@joys8998 Just released 0.11.0.411, enjoy! https://twitter.com/iRomeo_work/status/1386031601927213057?s=20
