### ISSUE TITLE
Syntax support for Snakemake 6.x 'module' and 'use' concepts

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/snakecharm#355]
Syntax support for Snakemake 6.x 'module' and 'use' concepts. We need at least basic syntax highlighting.

**Comment by iromeo** [comment]
In current master not everything is parsed properly:

![image](https://user-images.githubusercontent.com/72933/127028983-be12d369-32a4-4bfa-ac81-1673a5352496.png)
![image](https://user-images.githubusercontent.com/72933/127029122-7f433b27-08e4-4952-b2bc-3faa4e3e0ffe.png)

**Comment by dakochik** [comment]
'module' and 'use' sections highlighting is done:

![module use highlighting](https://user-images.githubusercontent.com/55440084/127130323-e88f0c77-b11c-45b1-8edb-9a10b3cc34bc.PNG)
