### ISSUE TITLE
File associations are lost on IDE restart

### ISSUE THREAD

**Issue by dievsky** [JetBrains-Research/snakecharm#357]
Each time I close and launch PyCharm, the file association for `*.smk` files is dropped and has to be established manually (context menu - Associate with File Type - Snakemake Pipeline). Curiously, `Snakemake` file association is not dropped.

I also get "Error Loading Project: Cannot load facet Snakemake" on every startup.

* PyCharm 2020.1.5 (Professional Edition) Build #PY-201.8743.20, built on December 1, 2020 (but it happened on earlier versions too).
* SnakeCharm 0.7.0.209.

**Comment by iromeo** [comment]
@dievsky Hi, since 0.7.0.209 there was 3 major updates - 0.8, 0.9, 0.11. Could you please install latest PyCharm 2021.1.x and latest plugin 0.11.x ?

**Comment by dievsky** [comment]
Looks like the latest plugin version `2021.2.0.414` doesn't suffer from this problem (or maybe the problem was with the IDE, which I also updated to `PyCharm 2021.1.1 (Professional Edition) Build #PY-211.7142.13, built on April 21, 2021`.

However, the latest version also doesn't recognize `rules`, `expand`, and other Snakemake builtins. Is this a known problem? I can create a new issue if it's not.

**Comment by iromeo** [comment]
@dievsky please ensure that snakemake framework is enabled in ide settings, “supported framewoks” menu item

**Comment by dievsky** [comment]
After turning the framework on, `expand` is now recognized, but `rules` are still not.

**Comment by dievsky** [comment]
After turning the framework on, `expand` is now recognized, but `rules` are still not.

**Comment by iromeo** [comment]
Update: after a remote session with @dievsky :
- snakemake 5.4.0, no snakemake-minimal; installed in anaconda ~2018 `base` env
- snakemake framework support uses a project interpreter
- 'rules' item is in a completion list, but all usages are marked as unresolved
- `config` also in completion, no unresolved error
- if change project sdk to snakemake 6.3.0 in separate conda env - all unresolved `rules` disappears

**Comment by iromeo** [comment]
Rules issue move to the new bug report - https://github.com/JetBrains-Research/snakecharm/issues/359

**Comment by iromeo** [comment]
I'm closing the ticket because the file associations issue was resolved after plugin & IDE update.
