### ISSUE TITLE
Snakemake 6.5.x - unresolved 'rules.' warning

### ISSUE THREAD

**Issue by dakochik** [JetBrains-Research/snakecharm#367]
Hello, I'm using WSL on Windows 10 with Ubuntu. 
I've installed Anaconda v. 4.10.3 and Snakemake v. 6.5.1.
When I chose python interpreter with snakemake module inside from WSL with Ubuntu as PyCharm (professional edition v. 2021.1.3) python interpreter(as mentioned [here](https://www.jetbrains.com/help/pycharm/configuring-python-interpreter.html#add_new_project_interpreter)) and oppened the project(https://github.com/JetBrains-Research/chipseq-smk-pipeline-edu#configure-pipeline) i got the following warnings:
![issue](https://user-images.githubusercontent.com/55440084/124280760-bf1b3f80-db51-11eb-8196-83c61fd434cc.png)

Snakemake support is enabled.
However, resolve and code completion are working correctly for `expand(...)`

**Comment by iromeo** [comment]
P.S: the inspection false positive is due to `snakemake/commons.py` -> `snakemake/commons/__init__.py` refactoring in snakemake 6.5

**Comment by iromeo** [comment]
Please check that issue is resolved in the latest `2021.2.424` release

**Comment by dakochik** [comment]
That works, thank you!
