### ISSUE TITLE
Some inspections works for rule sections, but not for workflow top-level sections

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/snakecharm#384]
E.g. not inspection warnings:

* Only one argument is allowed for 'containerized' section. 
* Section 'containerized' does not support keyword arguments 
for 
```
containerized: "docker://continuumio/miniconda3:4.4.10", "ffff", foo="ddd"

rule all:
   input: ""
```

Affected inspections: SmkSectionUnexpectedKeywordArgsInspection, SmkSectionMultipleArgsInspection

**Comment by dakochik** [comment]
Fixed:

![top-level inspections](https://user-images.githubusercontent.com/55440084/126610006-178ac7d5-1dcb-4547-b1e8-2765f00615db.gif)
