### ISSUE TITLE
Benchmark may omit wildcards from output

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/snakecharm#400]
Seems is a valid case:
```

rule a:
    output:
        "test.{x}.txt"
    benchmark:
        "benchmarks/test.txt"
    shell:
        "touch {output}"
```

![image](https://user-images.githubusercontent.com/72933/127030416-ea532a4d-8860-429e-bd8a-143df1c3b771.png)

**Comment by iromeo** [comment]
Please ensure runtime behaviour. Benchmark generates a table, so maybe for wildcard rules it appends all execution results into this table.

**Comment by dakochik** [comment]
Attempt to execute the rule (`snakemake -c1 test.a.txt`) leads to SE:  
`
Not all output, log and benchmark files of rule a contain the same wildcards. This is crucial though, in order to avoid that two or more jobs write to the same file.
`
