### ISSUE TITLE
Support modules and use in statement mover

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/snakecharm#406]
See `SmkStatementMover`, related to #355

**Comment by dakochik** [comment]
Fixed:

![module mover](https://user-images.githubusercontent.com/55440084/128991348-591297b8-4d8e-4f96-be72-bfa24e473b42.gif)
![use mover](https://user-images.githubusercontent.com/55440084/128991807-2a1c0a3c-5327-4ef6-ae77-cdd59db5fa6b.gif)
