### ISSUE TITLE
Inspection for execution sections in 'use' section

### ISSUE THREAD

**Issue by dakochik** [JetBrains-Research/snakecharm#408]
If an execution section appears in 'use' section, we are getting misleading message:

![127199324-845f9c69-9799-4e09-9aab-b8e78e5c5fd8](https://user-images.githubusercontent.com/55440084/127272989-56933eb4-0e85-4157-a229-681cef58a8f4.png)

But in this case, snakemake prints an error with message: "Unexpected keyword shell in rule definition"
So, we need to add a more appropriate message.
Related to #355

**Comment by iromeo** [comment]
Similar for subworflows:
```
subworkflow foo:
    input: ""
```
See `..../python3.8/site-packages/snakemake/parser.py`
```python
        if is_name(token):
            try:
                if token.string == "snakefile":
                    self.has_snakefile = True
                if token.string == "workdir":
                    self.has_workdir = True
                for t in self.subautomaton(token.string).consume():
                    yield t
            except KeyError:
                self.error(
                    "Unexpected keyword {} in "
                    "subworkflow definition".format(token.string),
                    token,
                )
```

**Comment by iromeo** [comment]
For `module`
```
    def block_content(self, token):
        if is_name(token):
            try:
                if token.string == "snakefile":
                    self.has_snakefile = True
                if token.string == "meta_wrapper":
                    self.has_meta_wrapper = True
                for t in self.subautomaton(token.string).consume():
                    yield t
            except KeyError:
                self.error(
                    "Unexpected keyword {} in "
                    "module definition".format(token.string),
                    token,
                )
```

**Comment by dakochik** [comment]
Fixed:

![unrecognized section #1](https://user-images.githubusercontent.com/55440084/128990510-64d924b1-6f42-4acf-880e-467288dc5e00.PNG)
![unrecognized section #2](https://user-images.githubusercontent.com/55440084/128990525-f1fbd968-0488-4173-be6e-b0e51511788c.PNG)

**Comment by iromeo** [comment]
@dakochik Please add short feature demo (png or gif)

**Comment by dakochik** [comment]
Done: 

![unused log section use case](https://user-images.githubusercontent.com/55440084/129573972-8ad7e6b3-73b7-4f29-8c18-4f56e332f01b.PNG)
