### ISSUE TITLE
add reference for 'snakefile:' in module declaration

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/snakecharm#409]
E.g. we could resolve/complete `other_workflow/Snakefile`path  using project *.smk and Snakfile files
```
module other_workflow:
    snakefile: "other_workflow/Snakefile"
```

**Comment by iromeo** [comment]
@dakochik Please add short  GIF demo

**Comment by dakochik** [comment]
Done:

![module file resolve](https://user-images.githubusercontent.com/55440084/129571191-ab44e786-0d21-4c4c-ae1e-3b40b5132832.gif)
