### ISSUE TITLE
Inspection warn of use pattern overloads several rules with a single name

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/snakecharm#411]
```
use rule * from rule_355_module as rule_foo 
```
>  snakemake would use as rule_foo only the last rule in imported module rule_355_module

Related to #355

**Comment by dakochik** [comment]
Done:
![411](https://user-images.githubusercontent.com/55440084/139528050-a8a5b968-4d98-4c38-b060-7ef3d828ff4d.gif)

**Comment by iromeo** [comment]
False positive:

![image](https://user-images.githubusercontent.com/72933/139597156-dcbdedea-466d-4637-8628-55b353a2cfca.png)

Here no 'as' and it isn't need (code works at runtime)

**Comment by dakochik** [comment]
FP fixed:
![image](https://user-images.githubusercontent.com/55440084/140293960-b44a875a-f822-464e-849b-9006d4264a7f.png)
