### ISSUE TITLE
Syntax highlighting/recognition of Rule Inheritance

### ISSUE THREAD

**Issue by JoshLoecker** [JetBrains-Research/snakecharm#430]
Snakemake 6.0 released a new feature called [Rule Inheritance](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#rule-inheritance), which allows for the re-use of any components of a rule, except for the shell/run/script/etc. PyCharm does not recognize this as acceptable syntax, and shows errors around the `use rule _ as _ with: ` regions. I have included a screenshot of what I am attempting to show

<img width="322" alt="Screen Shot 2021-10-07 at 3 39 53 PM" src="https://user-images.githubusercontent.com/47901540/136458776-3520bcd3-766d-4a25-bfcc-3be6105dbb98.png">

I was hoping for the snake charm plugin to not see these types of rules as syntax errors

**Comment by iromeo** [comment]
Hi @JoshLoecker, we've already added 'use' support in our master, which will be released with the next plugin update (I expect ~ december). If you'd like to get it now we could publish beta build this week. See covered features in https://github.com/JetBrains-Research/snakecharm/issues?q=is%3Aissue+milestone%3A%22next+major%22+is%3Aclosed

**Comment by iromeo** [comment]
@JoshLoecker Add `EAP` channel as written at https://github.com/JetBrains-Research/snakecharm/blob/master/README.md#eap-updates

![image](https://user-images.githubusercontent.com/72933/139597020-bfe4037e-d76a-4437-8446-7faf3bfa9a96.png)

And finally:
![image](https://user-images.githubusercontent.com/72933/139597251-516b70d7-e1a8-48ee-9f7f-29f630267527.png)

**Comment by iromeo** [comment]
Released as part of 2021.2.657 and will be included in coming 2021.3.x build
