### ISSUE TITLE
Code Inspection: Resources must be int values

### ISSUE THREAD

**Issue by sharkovadarya** [JetBrains-Research/snakecharm#44]
According to Snakemake [docs](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#resources), resources must be int values:

    resources: mem_mb=100

or callables that return int values.

**Comment by iromeo** [comment]
Not obligatory any more in snakemake 0.5.15, see https://snakemake.readthedocs.io/en/stable/project_info/history.html#id6
