### ISSUE TITLE
Keywords highlighting

### ISSUE THREAD

**Issue by dakochik** [JetBrains-Research/snakecharm#454]
Sometimes python highlighting overrides snakemake highlighting:  

![image](https://user-images.githubusercontent.com/55440084/147657278-a5bb8cb1-6e50-4b31-9b25-9287ad8a15b1.png)

**Comment by iromeo** [comment]
P.S: Workaround applied - use same python highlighting attribute for Python & Snakemake. So if it is changed in python, will be modified in Snakemake color scheme
