### ISSUE TITLE
Make plugin compatible with PyCharm 2022.1

### ISSUE THREAD

**Issue by bridgream** [JetBrains-Research/snakecharm#487]
Currently, SnakeCharm cannot be installed on PyCharm 2022.1. It would be great to have our plugin updated. 

Please let me know if there's anything I can help. I don't have much experience with Java, but I'd love to help test.

**Comment by jonas-eschle** [comment]
Hi, what's the status of this? I've seen that it was added to next release, but there seems to be still quite a bit ongoing. Can we maybe release this fix ASAP (since it is currently broken for anyone with the newest PyCharm version)

**Comment by iromeo** [comment]
New plugin released - https://github.com/JetBrains-Research/snakecharm/releases/tag/v2021.3.661
