### ISSUE TITLE
JetBrains Gateway support

### ISSUE THREAD

**Issue by ohickl** [JetBrains-Research/snakecharm#504]
Hi,
I am using JetBrains Gateway (2023.1 EAP atm) for remote development of a.o. Snakemake workflows but SnakeCharm hasn't been supported for some time. It would be very useful to have it back, are there plans to support it again?
Or did I maybe just overlook a possibility to use it despite the Marketplace/Plugins panels telling me its incompatible?

Best 

Oskar

**Comment by iromeo** [comment]
@ohickl I've just checked Gateway. It is possible to create a PyCharm based environment through it, connect there and install Snakecharm plugin in the remote environment.

It isn't supposed that you install SnakCharm as a plugin directly into Gateway application. Gateway provides you a thin client which communicates with PyCharm/etc IDE running on remote machine. So Gateway app allows to open a window like remote desktop window connected to the remote machine with PyCharm. Then you can install any supported plugins into the remote PyCharm instance, including SnakeCharm plugin
