### ISSUE TITLE
Current version of SnakeCharm is incompatible with PyCharm 2023.1

### ISSUE THREAD

**Issue by KatSteinke** [JetBrains-Research/snakecharm#505]
Just a heads-up again, PyCharm 2023.1 came out and is giving me compatibility warnings with SnakeCharm - I'm assuming SnakeCharm will break when I update, so this is making me hold off for now...

**Comment by iromeo** [comment]
Thx for the issue, I will update the plugin ASAP. I assume by the end of this week everything wo;; be compatible.

**Comment by iromeo** [comment]
Fixed. Updated plugin is already available for download.
