### ISSUE TITLE
Show notice on deprecated features

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/snakecharm#508]
E.g.:

* `dynamic` will not be available after 7.32.4 (see https://github.com/snakemake/snakemake/commit/b69786cd2ac054bc227e008267e163070e1cecde#diff-a4bcd796d9ae03f8be3597dd3f85b5ac873f52efc71b3d0790cfb566d9725330). Review #396 and #397

**Comment by Xewar313** [comment]
Deprecated features include are:
version [5.11.0] deprecates `singularity` keyword
version [5.4.0] deprecates `dynamic` keyword
version [8.0.0] removes `dynamic`, `version`, `subworkflow` keywords

**Comment by iromeo** [comment]
Examples:

Examples:

<img width="846" alt="image" src="https://github.com/user-attachments/assets/4457e794-8a74-4177-8cb0-e13735ed12ac">
<img width="795" alt="image" src="https://github.com/user-attachments/assets/310f2927-0fe7-4fb3-b176-1edd07639830">

<img width="979" alt="image" src="https://github.com/user-attachments/assets/0b3bc171-6aba-4b1f-8549-ae3435b0f35a">

**Comment by iromeo** [comment]
Snakemake Language Version could be configured in PyCharm Settings | Languages and Frameworks | Snakemake

**Comment by iromeo** [comment]
Snakemake API description is bunded in plugin and could be found in `extra/snakemake_api.yaml` file in pluign folder
