### ISSUE TITLE
Snakecharm does not recognize localrule directive

### ISSUE THREAD

**Issue by Xewar313** [JetBrains-Research/snakecharm#524]
Version 7.25.0 introduced localrule directive, which is not recognized by Snakecharm https://github.com/snakemake/snakemake/pull/2180

**Comment by iromeo** [comment]
docs: https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#local-rules

alternative to `localrules`

Example:
```
rule all:
    input: ...
    localrule: True

rule foo:
    ...
    localrule: True

rule bar:
    ...
```

**Comment by iromeo** [comment]
fixed in https://github.com/JetBrains-Research/snakecharm/commit/4bf1d4df2df706bf36e8b96f0f28467f977cea20
