### ISSUE TITLE
Multiple functions are not recognized by snakecharm

### ISSUE THREAD

**Issue by Xewar313** [JetBrains-Research/snakecharm#526]
Snakecharm does not recognize multiple functions, such as `lookup`, `branch`, `evaluate`, `update`, `exists`, `glob_wildcards`.

**Comment by iromeo** [comment]
> lookup, branch , evaluate, exists

See https://github.com/JetBrains-Research/snakecharm/issues/548

> update

Already fixed - https://github.com/JetBrains-Research/snakecharm/issues/537

> glob_wildcards

Docs - https://snakemake.readthedocs.io/en/stable/project_info/faq.html#how-do-i-run-my-rule-on-all-files-of-a-certain-directory
Comes from `io.py` so if python SDK is configured, should work. Succesfully resolved in:
```
def aggregate_input(wildcards):
    checkpoint_output = checkpoints.clustering.get(**wildcards).output[0]
    return expand("post/{sample}/{i}.txt",
           sample=wildcards.sample,
           i=glob_wildcards(os.path.join(checkpoint_output, "{i}.txt")).i)


# an aggregation over all produced clusters
rule aggregate:
    input:
        aggregate_input
    output:
        "aggregated/{sample}.txt"
    shell:
        "cat {input} > {output}"
        ```
