### ISSUE TITLE
Support highlighting for arguments of format strings

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/snakecharm#53]
Snakemake automatically substitutes input, output, wildcards, etc. objects into strings used in input/output/message/shell, etc. sections. So it is a bit similar to f-strings appeared in python 3.6. At the moment no highlighting is substitution syntax is provided:
 
![image](https://user-images.githubusercontent.com/72933/58317807-3fbdcc80-7e1f-11e9-8bb5-701202f45f94.png)

Let's support highlighting similar to that which is provided by PyCharm for python f-strings, e.g.:

![image](https://user-images.githubusercontent.com/72933/58314553-688e9380-7e18-11e9-894c-ed2f3188c998.png)

P.S: we cannot use f-strings instead of ordinary strings in snakemake due to undefined variable errors, some vars appear lately on runtime

**Comment by iromeo** [comment]
Features like #43 could be easily implemented if we will detect substitution at parser level (like f-string support in PyCharm)

**Comment by iromeo** [comment]
Format strings use Python Mini Language Format, see  https://docs.python.org/3/library/string.html

Let's try to implement this using language injection approach.
* here format language is much more simple than syntax of f-strings
* mini language format isn't a valid python, e.g. in `{foo.some_dict[key]}` quotes around key are omitted
* we'd like to support this not for all strings in *.smk file, but only for some cases, e.g. args of sections, "shell" call, etc.
* we don't need to many features there, e.g. highlighting, completion, resolve, inline/extract param are enough
* completion/resolve isn't very complicated there, not required to make python completion work there

**Comment by iromeo** [comment]
Some examples:

Wildcards regexp constraints:
```
rule index_bams:
    input: '{anywhere}/{sample}.bam'
    output: '{anywhere}/{sample, [^/]*}.bam.bai'
    wrapper: '0.31.1/bio/samtools/index'

```

Escaped `{` and `}`:
```
rule bam_qc_pbc_nrf:
    input: rules.bam_to_pileup.output
    output: 'qc/pbc_nrf/{sample}.pbc_nrf.tsv'
    params:
          tmp_dir='tmp'
    shell: '''
mkdir -p {params.tmp_dir} &&
(T=$'\\t'
>&2 echo "TotalReadPairs${{T}}DistinctReadPairs${{T}}OneReadPair${{T}}TwoReadPairs${{T}}\
NRF=Distinct/Total${{T}}PBC1=OnePair/Distinct${{T}}PBC2=OnePair/TwoPair"

cat {input} | \
    sort -k1,1 -k3,3n -k2,2n -k6,6 -T {params.tmp_dir} | \
    awk -v OFS='\\t' '{{print $1,$2,$3,$6}}' | uniq -c | \
    awk 'BEGIN{{mt=0;m0=0;m1=0;m2=0}}
    ($1==1){{m1=m1+1}} ($1==2){{m2=m2+1}} {{m0=m0+1}} {{mt=mt+$1}}
    END{{
        if (mt!=0){{m0_t=m0/mt}} else {{m0_t=-1.0}};
        if (m0!=0){{m1_0=m1/m0}} else {{m1_0=-1.0}};
        if (m2!=0){{m1_2=m1/m2}} else {{m1_2=-1.0}};
        printf "%d\\t%d\\t%d\\t%d\\t%f\\t%f\\t%f\\n",mt,m0,m1,m2,m0_t,m1_0,m1_2;
    }}') > {output}
    '''
```

**Comment by nekit-000000** [comment]
Identifiers of string language in input, output, etc. rule sections turn into wildcards in snakemake
See: snakemake/io.py:565
e.g. _sample_ will be considered as wildcard in 
```
rule NAME:
   input: "{sample}.txt"

```

**Comment by iromeo** [comment]
Related PyCharm bug - https://youtrack.jetbrains.com/issue/PY-37374

**Comment by iromeo** [comment]
Done

![image](https://user-images.githubusercontent.com/72933/62884616-adeb9e80-bd3f-11e9-8b24-536fa7381c2c.png)

![image](https://user-images.githubusercontent.com/72933/62884658-c491f580-bd3f-11e9-8973-a2556a1ff8c1.png)
