### ISSUE TITLE
SnakeCharm not compatible with PyCharm version 2024.2

### ISSUE THREAD

**Issue by LottePronk** [JetBrains-Research/snakecharm#532]
Thanks for this plugin, it's very useful. Unfortunately, the current version of the plugin cannot be used with PyCharm version 2024.2

**Comment by gilmorera** [comment]
+1 @iromeo  @Xewar313  any updates on when the 2024.2 release will be available?

**Comment by iromeo** [comment]
@LottePronk @gilmorera Thx for reporting. We will update it in the next two weeks. I'm sorry for the inconvenience.

**Comment by iromeo** [comment]
Status update: The fix requires a bit more time than I expected due to internal changes in the platform API and plugin-building scripts. I'm already working on this.  

P.S:  As a temporary workaround, you could use PyCharm 2024.1 version for your snakemake projects and 2024.2+ for other projects.

**Comment by iromeo** [comment]
2024.2.1 just released, see release notes https://github.com/JetBrains-Research/snakecharm/releases/tag/v2024.2.1

**Comment by gaurav** [comment]
Thank you so much for fixing this issue!
