### ISSUE TITLE
Inspection: wildcards in shell script can be used only with `wildcards.` prefix.

### ISSUE THREAD

**Issue by olegs** [JetBrains-Research/snakecharm#57]
Snakemake error message is quite misleading, 

This won't work with strange error `sample` is unknown. 
```
rule trim_single_fastq:
    input: os.path.join(config['fastq_dir'], '{sample}.fastq')
    output: 'cleaned/{sample}_se.fastq'
    threads: 4
    conda: 'envs/bio.env.yaml'
    shell: 'trim_galore --cores {threads} --nextera {input} -o cleaned/ &> {log}; ' \
           'mv cleaned/{sample}_val.fq {output}'
```

Changing `cleaned/{sample}_val.fq` to `cleaned/{wildcards.sample}_val.fq` fixes the problem.

**Comment by iromeo** [comment]
Done

![image](https://user-images.githubusercontent.com/72933/64910627-16ec7a80-d721-11e9-80df-429b642a220d.png)

![image](https://user-images.githubusercontent.com/72933/64910634-28ce1d80-d721-11e9-9bd8-65c0ecc9e488.png)
