### ISSUE TITLE
Inspection: trailing comment at the end of Snakefile

### ISSUE THREAD

**Issue by olegs** [JetBrains-Research/snakecharm#58]
Consider the end of snake file containing the following:
```
rule all:
    input:
         multiqc_fastq='multiqc/fastqc/multiqc.html',
```
Trailing comma leads to en error.

**Comment by winni2k** [comment]
Just to clarify: Is the correct behavior that this should not be an error?

**Comment by iromeo** [comment]
@olegs Is it really introduce an error?

I've tried

```
rule all:
    output:
        foo=touch('foo'),
```
and
```
rule all:
    output:
        foo=touch('foo'),
    params:
        threads=1
```
both works ok using snakemake 5.4.0

**Comment by winni2k** [comment]
Ok, so I think what @olegs may be trying to say is that the trailing commas are marked red in Pycharm, but trailing commas are actually fine for the snakemake interpreter. In any case, I certainly see this, and I find it a minor annoyance.

**Comment by winni2k** [comment]
To clarify, given the following rule definition:

```
rule my_rule:
    input: 'my_input.file',
    output: 'my_output.file'
    shell: 'echo hi world'
```

In the above example, `output:` is underlined in red. The tooltip reads "Unresolved reference 'output'"

**Comment by iromeo** [comment]
@winni2k Thank you for the test case, indeed SnakeCharm plugin highlights the trailing commas as red when they are on the same line as a section name, see the screenshot: error on 4-th line, not on 3-rd
![image](https://user-images.githubusercontent.com/72933/60462532-39a6e100-9c52-11e9-8e5d-174e285aa960.png)

**Comment by iromeo** [comment]
Fixed, will be available in next release 0.4.x

**Comment by iromeo** [comment]
SnakeCharm doesn't warn of `trailing comma`  for code which fails on runtime
![image](https://user-images.githubusercontent.com/72933/61941081-717a1d80-af9f-11e9-9819-e4292c0ea5e9.png)
```
# $ source activate snakemake
# $ snakemake  --use-conda --cores 8

configfile: "config.yaml"
workdir: config['work_dir']

include: "step1_raw_qc.smk"
include: "step2_alignment.smk"
include: "step3_reads_coverage.smk"

rule all:
    input:
         rules.step1_raw_qc_results.input,
         rules.step2_alignment_results.input,
         # rules.step3_reads_coverage_results.input
```

**Comment by iromeo** [comment]
But snakemake doesn't fail if I add empty line at the end of file
![image](https://user-images.githubusercontent.com/72933/61941368-fe24db80-af9f-11e9-80d9-7d289bcce0b5.png)

**Comment by winni2k** [comment]
I don't think this is relevant to the comma question as both of these inputs fail with a syntax error on my machine:

```
rule all:
     input:
         'bla'
	 # bla2
```

```
rule all:
     input:
         'bla',
	 # bla2
```

Perhaps this is a bug in the snakemake interpreter?  It appears the comment is necessary in order for this to be called a syntax error.

**Comment by winni2k** [comment]
This also fails:

```

rule all:
     input:
         'bla'

# bla2
```

I think it must be something to do with a file ending in a commented line?

**Comment by iromeo** [comment]
@winni2k Yes, looks like some bug in snakemake

**Comment by iromeo** [comment]
![image](https://user-images.githubusercontent.com/72933/102199007-22a29000-3ed4-11eb-8838-7fe3d5145075.png)

**Comment by olegs** [comment]
Thanks for fixing this!
