### ISSUE TITLE
Multiple declarations of the same section

### ISSUE THREAD

**Issue by sharkovadarya** [JetBrains-Research/snakecharm#71]
Example:

    rule NAME:
        input: "input.txt"
        output: "output.txt"
        params: a="a", b="b"
        params: a="a1"
        run:
            print(f"{params.a}")

The output is "a" since only the first occurrence is applied.

Desired outcome: code highlighted as an unused statement.

**Comment by iromeo** [comment]
Could you add a screenshot of how this example will be highlighted?

**Comment by sharkovadarya** [comment]
![image](https://user-images.githubusercontent.com/12707841/60589930-5d2d7100-9da3-11e9-9489-6b4201ce8509.png)

The second (and all subsequent) `params` section is highlighted as unused code.
