### ISSUE TITLE
Keyword arguments duplication

### ISSUE THREAD

**Issue by sharkovadarya** [JetBrains-Research/snakecharm#72]
Example:
 
    params: a="a1", a="a2"

results in the following syntax error: `keyword argument repeated`.

**Comment by iromeo** [comment]
![image](https://user-images.githubusercontent.com/72933/60678521-6b57bc00-9e8d-11e9-8256-d9d00ddd206c.png)

**Comment by iromeo** [comment]
Please leave highlighting only on keyword arg name, because no errors in arg value. Otherwise looks not very clear, like some missing comma or other syntax error

![image](https://user-images.githubusercontent.com/72933/61997572-1b46d080-b0ac-11e9-8d04-9b8aca16f912.png)

**Comment by iromeo** [comment]
Done 
![image](https://user-images.githubusercontent.com/72933/62644206-405ffc80-b952-11e9-8697-d5d3f26bab28.png)
