### ISSUE TITLE
Shadow settings documentation

### ISSUE THREAD

**Issue by nekit-000000** [JetBrains-Research/snakecharm#73]
![Screenshot from 2019-07-02 13-08-11](https://user-images.githubusercontent.com/25721619/60504584-862e0300-9cca-11e9-87d1-92285df9cd75.png)

**Comment by iromeo** [comment]
Fixed

**Comment by iromeo** [comment]
Documentation popup doesn't work in case of single-quoted string:
```
rule foo:
   shadow: 'minimal'
```

**Comment by iromeo** [comment]
see #157
