### ISSUE TITLE
Inspection: subworkflow 'workdir', 'snakefile', 'configfile' could accept only single arg

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/snakecharm#83]
Ensure that it is true. Better to implement using annotator and highlight as an syntax error

**Comment by iromeo** [comment]
Is related to #66

**Comment by iromeo** [comment]
@nekit-000000  Please add a screenshot, close the issue and mark it as done in  #90 task

**Comment by nekit-000000** [comment]
![Screenshot from 2019-07-05 15-05-37](https://user-images.githubusercontent.com/25721619/60721393-6c90f380-9f36-11e9-9705-9b027affa5d2.png)
