### ISSUE TITLE
Subworflow redeclaration inspection

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/snakecharm#88]
Warn if subworflow was imported with same name several times. The warning type (warning or error) and message should be consistent with runtime behaviour.

**Comment by iromeo** [comment]
@nekit-000000  Please add a screenshot, close the issue and mark it as done in  #90 task

**Comment by nekit-000000** [comment]
![Screenshot from 2019-07-05 10-46-35](https://user-images.githubusercontent.com/25721619/60721302-25a2fe00-9f36-11e9-83c9-a6f8f3a0f6a8.png)
